name: Daily Repository Update

on:
  schedule:
    - cron: '30 18 * * *'  # 18:30 UTC = 00:00 IST (next day)

jobs:
  automated-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing changes
    steps:
      - name: 21f1002409@ds.study.iitm.ac.in
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Crucial for write access
          fetch-depth: 0

      - name: Create timestamp file
        run: |
          echo "Daily update: $(date -u)" >> update_log.txt
          git config user.name "21f1002409"
          git config user.email "21f1002409@ds.study.iitm.ac.in"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Daily automated update'
          branch: main
          commit_author: 'DevSync Bot <21f1002409@ds.study.iitm.ac.in>'
