name: Daily Repository Update

on:
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a change
        run: |
          echo "Last updated on $(date)" > last-updated.txt

      - name: 21f1002409@ds.study.iitm.ac.in
        run: |
          git config --global user.name "21f1002409"
          git config --global user.email "21f1002409@ds.study.iitm.ac.in"
          git add last-updated.txt
          git commit -m "Automated daily update - $(date)"
          git push
